global using Localization_Service_Application.Common.Interfaces.ContactUsPageResourceManager;
global using Localization_Service_Application.Common.Interfaces.EmployeesPageResourceManager;
global using Localization_Service_Application.Common.Interfaces.ResourcesFile;
global using Localization_Service_Application.Common.Models.Dtos.ContactUs;
global using Localization_Service_Application.Common.Models.Dtos.Employees;
global using Localization_Service_Application.Common.Models.Dtos.HomePage;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using Localization_Service_Application.Common.Models.Dtos.Artcile;
global using Localization_Service_Application.Common.Interfaces.ArticlePageResourceManager;
global using Localization_Service_Application.Common.Models.Dtos.AboutUs;
global using Localization_Service_Application.Common.Interfaces.AboutUsPageResourceManger;
global using Localization_Service_Application.Common.Models.Dtos.ServicesPage;
global using Localization_Service_Application.Common.Interfaces.ServicesPageResourceManager;
global using Localization_Service_Application.Common.Models.Dtos.SubEmployeesPage;
global using Localization_Service_Application.Common.Interfaces.SubEmployeePageResourceManager;

