global using Localization_Service_Application.Common.Interfaces.EmployeesPageResourceManager;
global using Localization_Service_Application.Common.Interfaces.ResourcesFile;
global using Localization_Service_Application.Common.Models.Dtos.Employees;
global using Localization_Service_Infrastructure.Services.ResourceFileManager;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Localization;
global using Localization_Service_Domain.ResourcesFile.EmployeePage;
global using Localization_Service_Infrastructure.Services.EmployeesResourceManager;
global using Localization_Service_Application.Common.Models.Dtos.ContactUs;
global using Localization_Service_Application.Common.Interfaces.ContactUsPageResourceManager;
global using Localization_Service_Domain.ResourcesFile.ContactUs;
global using Localization_Service_Infrastructure.Services.ContactUsPageResourceManager;
global using Localization_Service_Application.Common.Models.Dtos.Artcile;
global using Localization_Service_Application.Common.Interfaces.ArticlePageResourceManager;
global using Localization_Service_Domain.ResourcesFile.ArticlePage;
global using Localization_Service_Infrastructure.Services.ArticlePageResourceManager;
global using Localization_Service_Application.Common.Models.Dtos.AboutUs;
global using Localization_Service_Application.Common.Interfaces.AboutUsPageResourceManger;
global using Localization_Service_Domain.ResourcesFile.AboutUsPage;
global using Localization_Service_Infrastructure.Services.AboutUsPageResourceManager;





